version: 2.1

orbs:
  cli: circleci/circleci-cli@volatile

commands:
  validate:
    description: >
      Users the CLI to validate a given orb yml
    parameters:
      orb-path:
        description: "Path to the orb to be validated."
        type: string
    steps:
      - run:
          name: "Validate whether this is a well-formed orb."
          command: circleci orb validate << parameters.orb-path >>

  pack:
    description: >
      *Experimental*
      Uses the CLI to pack an orb file structure
      into a single orb yml.
    parameters:
      source:
        description: "Path to the root folder of an unpacked orb."
        type: string
      destination:
        description: "Path including the filename to output the packed orb."
        type: string
    steps:
      - run:
          name: "Pack << parameters.source>>"
          command: |
            circleci config pack << parameters.source >> > << parameters.destination >>

  persist-orb-to-workspace:
    description: >
      Persists an orb yml between jobs in a workflow.
    parameters:
      orb-path:
        description: "Path to the orb to be persisted."
        type: string
      workspace-path:
        description: >
          Save the contents of the orb into the workspace at the
          given path. The value should include a trailing slash.
        type: string
    steps:
      - run:
          name: Save and orb to `<< parameters.workspace-path >>`
          command: |
            mkdir -p << parameters.workspace-path >>
            cp << parameters.orb-path >> << parameters.workspace-path >>
      - persist_to_workspace:
          name: "Persist orb to `<< parameters.workspace-path >>` because that value was passed as `parameters.workspace-path`."
          root: .
          paths:
            - << parameters.workspace-path >>

  increment:
    description: >
      Uses the CLI to increment the version of an orb in the registry.
      If the orb does not have a version yet it starts at 0.0.0
    parameters:
      orb-path:
        description: "Path to an orb."
        type: string
      namespace:
        description: "Namespace the orb lives under."
        type: string
      orb-name:
        description: "Name of the orb to increment.;"
        type: string
      segment:
        description: "The semver segment to increment 'major' or 'minor' or 'patch'"
        type: enum
        enum: ["major", "minor", "patch"]
      token-variable:
        description: "The env var containing your token. Pass this as a literal string such as `$ORB_PUBLISHING_TOKEN`. Do not paste the actual token into your configuration."
        type: string
    steps:
      - run:
          name: >
            Increment << parameters.segment >> segment of orb at << parameters.orb-path >>
            NOTE: this currently assumes you are publishing to the registry at circleci.com
          command: |
            circleci orb publish increment \
            << parameters.orb-path >> \
            << parameters.namespace >>/<< parameters.orb-name >> \
            << parameters.segment >> \
            --token << parameters.token-variable >>

  publish:
    description: >
      Uses the CLI to publish an orb to the registry.
    parameters:
      orb-path:
        description: "Path to an orb."
        type: string
      orb-ref:
        description: >
          A fully-qualified reference to an orb. This takes the form namespace/orb@version.
          NOTE: To publish a dev version prefix the version with 'dev:' like so namespace/orb@dev:label
        type: string
      token-variable:
        description: "The env var containing your token. Pass this as a literal string such as `$ORB_PUBLISHING_TOKEN`. Do not paste the actual token into your configuration."
        type: string
    steps:
      - run:
          name: >
            Publish orb at << parameters.orb-path >> to << parameters.orb-ref >>
            NOTE: this currently assumes you are publishing to the registry at circleci.com
          command: |
            circleci orb publish << parameters.orb-path >> << parameters.orb-ref >> --token << parameters.token-variable >>

jobs:
  pack-and-validate-orb:
    description: >
      Pack the contents of an orb for publishing
      and validate the orb is well-formed.
    parameters:
      path:
        description: >
          The root of where the code for the orb lives
          relative to the root of the repo.
        type: string
      workspace-path:
        description: >
          When provided, save the contents of the orb into
          the workspace at the given path. The value should
          include a trailing slash.
          Empty string (also the default value) is a no-op.
        type: string
        default: ""
      artifact-path:
        description: >
          When provided, save the contents of the orb as an
          artifact in the directory specified. The value should
          include a trailing slash.
          Empty string (also the default value) is a no-op.
        type: string
        default: ""
      destination-file-name:
        description: >
          The name of the file where the packed string will be stored.
          In most cases you can leave the default value of `orb.yml`.
        type: string
        default: "orb.yml"

    executor: cli/default
    steps:
      - run:
          name: "Starting the job: pack-and-validate-orb on the directory << parameters.path >>"
          command: |
            echo "parameters.workspace-path passed as: '<< parameters.workspace-path >>' (if the string is empty no workspace save will be attempted)"
            echo "parameters.artifact-path passed as: '<< parameters.artifact-path >>' (if the string is empty no artifact save will be attempted)"
            echo "parameters.destination-file-name passed as: '~/pack-and-validate-orb/<< parameters.destination-file-name >>'"
      - checkout
      - run:
          name: "Ensure /pack-and-validate-orb"
           # TODO: this is more fragile than is ideal
           # TODO: using this fixed path feels like a hack or a missing feature to have a small dose of shared state across the job that can be mutated at runtime
          command: |
            mkdir -pv ~/pack-and-validate-orb
      - pack:
          source: << parameters.path >>
          destination: ~/pack-and-validate-orb/<< parameters.destination-file-name >>
      - validate:
          orb-path: ~/pack-and-validate-orb/<< parameters.destination-file-name >>
      - when:
          condition: << parameters.workspace-path >>
          steps:
            - persist-orb-to-workspace:
                orb-path: ~/pack-and-validate-orb/<< parameters.destination-file-name >>
                workspace-path: << parameters.workspace-path >>
      - when:
          condition: << parameters.artifact-path >>
          steps:
            - store_artifacts:
                name: "Storing the artifact to << parameters.artifact-path >><< parameters.destination-file-name >>"
                path: ~/pack-and-validate-orb/<< parameters.destination-file-name >>
                destination: << parameters.artifact-path >><< parameters.destination-file-name >>

  publish-orb:
    executor: cli/default
    parameters:
      orb-ref:
        description: >
          A fully-qualified reference to an orb. This takes the form namespace/orb@version.
          NOTE: To publish a dev version prefix the version with 'dev:' like so namespace/orb@dev:label
        type: string
      workspace-path:
        description: "The directory relative to the workspace root where the orb file will be found. Should end in a trailing /"
        type: string
        default: ""
      token-variable:
        description: "The env var containing your token. Pass this as a literal string such as `$ORB_PUBLISHING_TOKEN`. Do not paste the actual token into your configuration."
        type: string
      file-name:
        description: "The name of the file where the packed string is stored. In most cases you can leave the default value."
        type: string
        default: "orb.yml"
      do-validation:
        description: "Boolean for whether to do validation. Default is true."
        type: boolean
        default: true
    steps:
      - when:
          condition: << parameters.workspace-path >>
          steps:
            - attach_workspace:
                at: .
      - unless:
          condition: << parameters.workspace-path >>
          steps:
            - run:
                name: "No workspace was passed."
                command: |
                  echo "No workspace was passed."
                  exit 1
      - when:
          condition: << parameters.do-validation >>
          steps:
            - validate:
                orb-path: << parameters.workspace-path >><< parameters.file-name >>
      - publish:
          orb-path: << parameters.workspace-path >><< parameters.file-name >>
          orb-ref: << parameters.orb-ref >>
          token-variable: << parameters.token-variable >>
